[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

; --- LIBRERIE DA SCARICARE IN AUTOMATICO ---
lib_deps = 
    ; Librerie per il sensore IMU
    https://github.com/adafruit/Adafruit_BNO08x.git

    ; Libreria per i motori passo-passo
    waspinator/AccelStepper
    
    ; Libreria per i sensori ToF multidimensionali VL53L5CX
    https://github.com/sparkfun/SparkFun_VL53L5CX_Arduino_Library.git

    ; Libreria per l'overclocking del Raspberry Pi Pico 2
    